### ISSUE TITLE
Performance view doesn't work for invalid fragments

### ISSUE THREAD

**Issue by Voycawojka** [Knotx/knotx-fragments-chrome-extension#102]
**Describe the bug**
Performance view doesn't work (all timestamps are 0) for invalid fragments

**To Reproduce**
1. Open the details of some **failed** fragment
2. Open the performance tab

**Expected behavior**
Timeline items are shown correctly and aren't all 0

**Comment by SzajekSzymon** [comment]
duplicated #84

**Comment by Voycawojka** [comment]
Closing as it's a duplicate
