### ISSUE TITLE
status (graph) panel

### ISSUE THREAD

**Issue by MichuP** [Knotx/knotx-fragments-chrome-extension#11]
**Description**
The purpose of this is to create the status panel of the plugin, on which the graph and log info will be shown. 

**Acceptance criteria**
1. The status panel contains:
  1.1 the graph, 
  1.2 a panel containing the raw log 
  1.3 a toggle allowing to show only the path of the graph that was processed (default view) or the entire graph
2. The graph has the following visualisation logic:
  2.1 Nodes processed successfully are green, error nodes are red. Nodes that were unprocessed are grey and the transition arrows to them are dashed. All other nodes (fallbacks, custom) are blue.
  2.2 The composite nodes green when all nodes within composite are green. They are red when at least one node of the composite was red. In cases that the
  2.3 When clicking on a specific node it gets "highlighted" (for example a thicker border)
  2.4 For the paths that processing happened and they ended in status other than success (red or blue), there should be an additional node (for example a dotted node with exclamation mark) indicating that this path was not handled properly (see examples for more clarity).
3. Clicking on a node shows a log of that node in the panel (AC 1.2). For now, all raw data available should be shown. There should be a possibility to change the log panel depending on the log action type (different "views" for different types). Clicking on the "composite node" should show a log as well. 

**Examples**
A typical "happy path":
![image](https://user-images.githubusercontent.com/7176770/73261254-fd2d6a80-41cb-11ea-8623-5b50aeee83af.png)

A path that had an error in it, however it was handled properly:
![image](https://user-images.githubusercontent.com/7176770/73261288-1209fe00-41cc-11ea-8cb7-fbcb1bae502e.png)

A path ending with an error that was not handled:
![image](https://user-images.githubusercontent.com/7176770/73261351-306ff980-41cc-11ea-82d0-8f09799e1d07.png)

![image](https://user-images.githubusercontent.com/7176770/73261377-3f56ac00-41cc-11ea-98b8-faed586b0a39.png)

A path where a fallback was not handled:
![image](https://user-images.githubusercontent.com/7176770/73261431-5a292080-41cc-11ea-8e2c-2dc0166b0a6a.png)

  

**Link to JIRA**
RND-773

**Comment by SzajekSzymon** [comment]
Please add those information to documentation.

**Comment by tomaszmichalak** [comment]
Documented: https://github.com/Knotx/knotx-fragments/tree/master/handler/consumer
