### ISSUE TITLE
graph performance panel

### ISSUE THREAD

**Issue by MichuP** [Knotx/knotx-fragments-chrome-extension#13]
**Description**
The purpose of this is to create the performance panel for the plugin

**Acceptance criteria**
1. The panel consists of:
  1.1 the graph,
  1.2 an input field allowing to provide a threshold for colouring the graph,
  1.3 tables containing performance of each node
2. The nodes of the graph are coloured only in two ways:
  2.1 Default grey
  2.2 Red - when a given node was executing longer than the threshold value provided b
3. The input field (AC 1.2) operates on milliseconds and has a default value of 500.
4. There are two tables / panels for displaying data:
  4.1 the first table lists all nodes for the graph selected. Each row contains the node id, node execution time, and node execution time / transaction execution time (%). Both single nodes and composites are displayed on the list. The table can be sorted based on each column. Clicking on a list row displays detailed log in a table below.
  4.2 the second table is used for displaying detailed information about the node / composite, provided it was selected in the previous table (AC 4.1)

**Simple mock**
![image](https://user-images.githubusercontent.com/7176770/73265957-3cf94f80-41d6-11ea-8fe7-4fb97e3ceeb5.png)

**Link to JIRA**
RND-775

**Comment by SzajekSzymon** [comment]
To discuss if its still valid.

**Comment by tomaszmichalak** [comment]
We decided to visualise this data as a gantt chart.
