### ISSUE TITLE
Main panel with fragments list

### ISSUE THREAD

**Issue by MichuP** [Knotx/knotx-fragments-chrome-extension#5]
**Description**
The purpose of this is to create the main fragments panel with list of panels, their statuses and basic sorting possibilities. 

**Acceptance criteria**
1. The main panel "fragments" is created and is selected by default when the plugin is opened
2. The panel contains list of all fragments for the page. Each fragment (row) contains the following info:
  2.1 fragment status
  2.2 fragment ID
  2.3 fragment type 
3. When clicking on a selected fragment:
  3.1 the fragment is highlighted in the browser
  3.2 the fragment is expended and the list of nodes is shown. Clicking on a specific node highlights the node in the browser.
4. There is a sorting possibility for the list (AC 1). By default the fragments are sorted by the processing order. One can also sort them by each column (id, type, status). Sorting by status gives the following ordering: errors, warnings (any transition that is not successful), success and unprocessed.
![image](https://user-images.githubusercontent.com/7176770/73247788-f691f980-41b1-11ea-967c-4a8459cb0b47.png)

**Link to JIRA**
RND-767

**Comment by SzajekSzymon** [comment]
What about sorting by type and status? in alphabetical order?

**Comment by tomaszmichalak** [comment]
Implemented.
