### ISSUE TITLE
Crash after clicking on fragments timeline

### ISSUE THREAD

**Issue by Voycawojka** [Knotx/knotx-fragments-chrome-extension#85]
**Describe the bug**
Sometimes the app crashes (blank screen is shown) after clicking on an item in the fragments timeline.

**To Reproduce**
It seems to not be deterministic

**Expected behavior**
Fragment corresponding to the timeline item is selected.

**Comment by SzajekSzymon** [comment]
Cannot reproduce. Please add steps to reproduce or video / screenshot.
