### ISSUE TITLE
Extension doesn't load when there's a lot of chrome tabs open

### ISSUE THREAD

**Issue by Voycawojka** [Knotx/knotx-fragments-chrome-extension#86]
**Describe the bug**
When there is a lot of chrome tabs open then the extension shows message about not using Knot.x even for the sites with knot.x debug data.

**To Reproduce**
1. Open a page with knot.x debug mode
2. Open a lot of chrome tabs (probably about 20+, possibly on multiple chrome windows)
3. Open the extension on the page from the first step 

**Expected behavior**
The app is loaded correctly

**Comment by SzajekSzymon** [comment]
tested on 20+ tabs.  Cannot reproduce.
