### ISSUE TITLE
Provide more descriptive naming for fragment ID

### ISSUE THREAD

**Issue by SzajekSzymon** [Knotx/knotx-fragments-chrome-extension#94]
currently fragments ids displayed in our extension are usless for developer. Think about more descriptive kind of ID. Maybe its a good time to make some changes in id naming on backend side. 

**Describe the solution you'd like**
Provide ids understandably and comfortable for developers.

**Comment by tomaszmichalak** [comment]
Suggested solution:
- exchange an unique id with task name (`fragment.configuration['data-knotx-task']`
- task name is no unique
- please add an additional column with fragment number (no sorting option here)

No backend changes are required.
