### ISSUE TITLE
remove unnecessary data from node details

### ISSUE THREAD

**Issue by SzajekSzymon** [Knotx/knotx-fragments-chrome-extension#97]
**Is your feature request related to a problem? Please describe.**
currently some nodes have empty properties in their details. 

- missing node - should has only one info: missing
- singleNode - should not has obvious info about subtasks which alway are empty

**Describe the solution you'd like**
Don't display unnecessary info about nodes.

**Comment by tomaszmichalak** [comment]
Please remember about unit tests.

**Comment by tomaszmichalak** [comment]
Missing node:
```
    "id": "8e48e363-8db1-4801-aa63-244682d77d5b",
    "label": "!",
    "status": "MISSING",
    "type": "SINGLE"
```
